### ISSUE TITLE
Relative paths always resolved from root

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-simulator#291]
1. Run:
```
hlx demo test
cd test
mkdir content
mv index.md content/.
mv helix_logo.png content/.
hlx up
```
2. Open http://localhost:3000/content

-> Image is not loaded, request is `/helix_logo.png` while it should be `/content/helix_logo.png`.

Using `![helix-logo](./helix_logo.png)` or `![helix-logo](helix_logo.png)` leads to the same error with `hlx up` - it works fine in the production environment.
Workaround: use full path `![helix-logo](/content/helix_logo.png)`

hlx-cli: v5.0.2
helix-simulator: v2.13.2

**Comment by kptdobe** [comment]
This is fascinating because `![helix-logo](../content/helix_logo.png)` works...

**Comment by kptdobe** [comment]
@tripodsan Any idea where this could be coming from ? The html source sent to the browser looks good (`<img src="./helix_logo.png" alt="helix-logo">` or `<img src="helix_logo.png" alt="helix-logo">`) but the request sent to the server is a GET `/helix_logo.png`. I do not get it...

**Comment by tripodsan** [comment]
try open: http://localhost:3000/content/

this is a general problem...also observe:

- https://lr.adobelanding.com/ecosystem vs
- https://lr.adobelanding.com/ecosystem/

In general, requests to directories w/o a slash at the end should be redirected to one with a slash.
most websites do this anyways. eg:

```
$ curl -sD- https://acrobat.adobe.com/us/en
HTTP/2 301
server: Apache
x-frame-options: SAMEORIGIN
location: https://acrobat.adobe.com/us/en/
content-length: 240
content-type: text/html; charset=iso-8859-1
cache-control: max-age=900
expires: Fri, 06 Sep 2019 03:31:20 GMT
date: Fri, 06 Sep 2019 03:16:20 GMT

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://acrobat.adobe.com/us/en/">here</a>.</p>
</body></html>
```

I think we should solve this in the VCL (but also in the simulator).
@trieloff  WDYT?

**Comment by kptdobe** [comment]
Arff, this is crazy! :)
But I still do not get what could be the source of the issue, at least in the simulator. Why the client browser behaves differently with or without the trailing `/`...

**Comment by tripodsan** [comment]
because on `/content/foo` the `base-href` of _this_ document is `/content`. so a relative link to `image.png` will be resolved to `/content/image.png`. 

but on `/content/foo/` the `base-href` of _this_ document is `/content/foo/`, and then the link is resolved to `/content/foo/image.png`. 

I guess there is a RFC for that...but it's pretty hard to find :-)

**Comment by trieloff** [comment]
> I think we should solve this in the VCL (but also in the simulator).

Adding a `301` for requests without an extension would be easy. Other than CQ or Apache, we won't know for sure that it is a directory, though.

**Comment by tripodsan** [comment]
> Other than CQ or Apache, we won't know for sure that it is a directory, though.

yes. but since we treat paths w/o extensions as directories and try to render `index.html` or `README.html`, we could assume such.
